// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *Cache) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Cache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *Cache_Expecter) Get(key interface{}) *Cache_Get_Call {
	return &Cache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *Cache_Get_Call) Run(run func(key string)) *Cache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Cache_Get_Call) Return(_a0 string, _a1 error) *Cache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cache_Get_Call) RunAndReturn(run func(string) (string, error)) *Cache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *Cache) Set(key string, value string) {
	_m.Called(key, value)
}

// Cache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Cache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *Cache_Expecter) Set(key interface{}, value interface{}) *Cache_Set_Call {
	return &Cache_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *Cache_Set_Call) Run(run func(key string, value string)) *Cache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Cache_Set_Call) Return() *Cache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *Cache_Set_Call) RunAndReturn(run func(string, string)) *Cache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// getHash provides a mock function with given fields: key
func (_m *Cache) getHash(key string) int {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for getHash")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Cache_getHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getHash'
type Cache_getHash_Call struct {
	*mock.Call
}

// getHash is a helper method to define mock.On call
//   - key string
func (_e *Cache_Expecter) getHash(key interface{}) *Cache_getHash_Call {
	return &Cache_getHash_Call{Call: _e.mock.On("getHash", key)}
}

func (_c *Cache_getHash_Call) Run(run func(key string)) *Cache_getHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Cache_getHash_Call) Return(_a0 int) *Cache_getHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cache_getHash_Call) RunAndReturn(run func(string) int) *Cache_getHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
